# RENAME FILE TO 'config.yml'
bot:
  token: MTIzNTI2NjY0Njg4OTg2MTE0MA.GxYwTw.kr38_9PQdkQOYwamr9vtG4xjuiCc9yeytBkrtA
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
